// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JGM2BTVusRU1dGxEVk3ZT0YlIhsPzSY',
    appId: '1:18206206938:web:88d4fd037971a3b4ccaee3',
    messagingSenderId: '18206206938',
    projectId: 'kibo-19064',
    authDomain: 'kibo-19064.firebaseapp.com',
    storageBucket: 'kibo-19064.firebasestorage.app',
    measurementId: 'G-29V4Z4DKGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wUi5danHVItBdEQudWCs_2_ePjzBUB4',
    appId: '1:18206206938:android:c19bb6bb8025844cccaee3',
    messagingSenderId: '18206206938',
    projectId: 'kibo-19064',
    storageBucket: 'kibo-19064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKGaqSqrZ9T1nk4jzV0B8iyS3d0o0Zao',
    appId: '1:18206206938:ios:ae5d8cc089ddc23fccaee3',
    messagingSenderId: '18206206938',
    projectId: 'kibo-19064',
    storageBucket: 'kibo-19064.firebasestorage.app',
    iosClientId: '18206206938-aa7gtqg02voeuu11mu6o7rpsc4bcqhr2.apps.googleusercontent.com',
    iosBundleId: 'com.lazzywhale.kibo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7JGM2BTVusRU1dGxEVk3ZT0YlIhsPzSY',
    appId: '1:18206206938:web:012a8aeb6184d286ccaee3',
    messagingSenderId: '18206206938',
    projectId: 'kibo-19064',
    authDomain: 'kibo-19064.firebaseapp.com',
    storageBucket: 'kibo-19064.firebasestorage.app',
    measurementId: 'G-0DNX0BLB5D',
  );
}
